version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: engagement_db
    environment:
      POSTGRES_DB: engagement_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  engagement-service:
    build: .
    container_name: engagement_service
    depends_on:
      - postgres
    ports:
      - "8087:8087"
    env_file:
      - .env

volumes:
  pgdata:
