// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	TokenID   string    `json:"token_id"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	Role      sql.NullString `json:"role"`
	Provider  string         `json:"provider"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
