definitions:
  handlers.CommentRequest:
    properties:
      content:
        type: string
    type: object
  handlers.UpdateRequest:
    properties:
      content:
        type: string
    type: object
  models.Comment:
    properties:
      content:
        type: string
      createdAt:
        type: string
      id:
        type: string
      updatedAt:
        type: string
      userID:
        type: string
      videoID:
        type: string
    type: object
info:
  contact: {}
  description: Graduation project - Video Streaming Platform with Microservices Architecture
  title: Scalable YouTube Clone API
  version: "1.0"
paths:
  /videos/{id}/comments:
    get:
      consumes:
      - application/json
      description: Get all comments for a video
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Comment'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      - BearerAuth: []
      summary: Get comments
      tags:
      - Comments
    post:
      consumes:
      - application/json
      description: Add a comment to a video if it exists
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: string
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Comment content
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/handlers.CommentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Comment'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      - BearerAuth: []
      summary: Add comment
      tags:
      - Comments
  /videos/{id}/comments/{commentId}:
    delete:
      consumes:
      - application/json
      description: Delete a user's own comment
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: string
      - description: Comment ID
        in: path
        name: commentId
        required: true
        type: string
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      - BearerAuth: []
      summary: Delete comment
      tags:
      - Comments
    put:
      consumes:
      - application/json
      description: Update a user's own comment
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: string
      - description: Comment ID
        in: path
        name: commentId
        required: true
        type: string
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Updated comment content
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/handlers.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      - BearerAuth: []
      summary: Update comment
      tags:
      - Comments
  /videos/{id}/dislike:
    post:
      consumes:
      - application/json
      description: Dislike or remove dislike on a video
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: string
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      - BearerAuth: []
      summary: Toggle dislike reaction
      tags:
      - Reactions
  /videos/{id}/like:
    post:
      consumes:
      - application/json
      description: Toggle like reaction for a video. Creates, deletes or updates like
        state for a user.
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: string
      - description: User ID from Auth
        in: header
        name: X-User-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      - BearerAuth: []
      summary: Like a video
      tags:
      - Reactions
securityDefinitions:
  BearerAuth:
    description: JWT token for authentication
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
